# Use root/example as user/password credentials
version: "3.1"

networks:
  app-tier:
    driver: bridge

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_USER: user
      MYSQL_PASSWORD: 123123
    networks:
      - app-tier
